export const student_names = [
  "John Smith",
  "Mary Graham",
  "James Kim",
  "Patricia Burke",
  "Robert Patel",
  "Jennifer Kennedy",
  "Michael Owen",
  "Linda Schmidt",
  "William Castillo",
  "Elizabeth Curtis",
  "David Christensen",
  "Barbara Arnold",
  "Richard Douglas",
  "Susan Willis",
  "Joseph Ray",
  "Jessica Sutton",
  "Thomas Ortega",
  "Sarah Jensen",
  "Charles Carlson",
  "Karen connor",
  "Christopher Marshall",
  "Nancy Mcdaniel",
  "Daniel Alvarez",
  "Lisa Avery",
  "Matthew Moreno",
  "Betty Bowman",
  "Anthony Medina",
  "Margaret Fowler",
  "Mark Brewer",
  "Sandra Hoffman",
  "Donald Carlton",
  "Ashley Silva",
  "Steven Pearson",
  "Kimberly Holland",
  "Paul Douglas",
  "Emily Fleming",
  "Andrew Jensen",
  "Donna Vargas",
  "Joshua Byrd",
  "Michelle Davidson",
  "Kenneth Hopkins",
  "Dorothy May",
  "Kevin Terry",
  "Carol Herrera",
  "Brian Wade",
  "Amanda Soto",
  "George Walters",
  "Melissa Curtis",
  "Edward Neal",
  "Deborah Caldwell",
  "Ronald Lowe",
  "Stephanie Jennings",
  "Timothy Barnett",
  "Rebecca Graves",
  "Jason Jimenez",
  "Sharon Horton",
  "Jeffrey Shelton",
  "Laura Barrett",
  "Ryan Obrien",
  "Cynthia Castro",
  "Jacob Sutton",
  "Kathleen Gregory",
  "Gary McKinney",
  "Amy Lucas",
  "Nicholas Miles",
  "Shirley Craig",
  "Eric Rodriquez",
  "Angela Chambers",
  "Jonathan Holt",
  "Helen Lambert",
  "Stephen Fletcher",
  "Anna Watts",
  "Larry Bates",
  "Brenda Hale",
  "Justin Rhodes",
  "Pamela Pena",
  "Scott Beck",
  "Nicole Newman",
  "Brandon Haynes",
  "Emma Mcfarland",
  "Benjamin Sparks",
  "Samantha Wiley",
  "Samuel Davidson",
  "Katherine Huang",
  "Gregory Kemp",
  "Christine Rivers",
  "Frank Ochoa",
  "Debra Bradshaw",
  "Alexander Foreman",
  "Rachel Johnson",
  "Raymond Williams",
  "Catherine Jones",
  "Patrick Brown",
  "Carolyn Davis",
  "Jack Miller",
  "Janet Wilson",
  "Dennis Moore",
  "Ruth Taylor",
  "Jerry Anderson",
  "Maria Thomas",
  "Tyler Jackson",
  "Heather White",
  "Aaron Harris",
  "Diane Martin",
  "Jose Thompson",
  "Virginia Garcia",
  "Adam Martinez",
  "Julie Robinson",
  "Henry Clark",
  "Joyce Rodriguez",
  "Nathan Lewis",
  "Victoria Lee",
  "Douglas Walker",
  "Olivia Hall",
  "Zachary Allen",
  "Kelly Young",
  "Peter Hernandez",
  "Christina King",
  "Kyle Wright",
  "Lauren Lopez",
  "Walter Hill",
  "Joan Scott",
  "Ethan Green",
  "Evelyn Adams",
  "Jeremy Baker",
  "Judith Gonzalez",
  "Harold Nelson",
  "Megan Carter",
  "Keith Mitchell",
  "Cheryl Perez",
  "Christian Roberts",
  "Andrea Turner",
  "Roger Phillips",
  "Hannah Campbell",
  "Gerald Parker",
  "Martha Evans",
  "Carl Edwards",
  "Jacqueline Collins",
  "Terry Stewart",
  "Frances Sanchez",
  "Sean Morris",
  "Ann Rogers",
  "Austin Reed",
  "Gloria Cook",
  "Arthur Morgan",
  "Jean Bell",
  "Lawrence Murphy",
  "Kathryn Bailey",
  "Jesse Rivera",
  "Alice Cooper",
  "Dylan Richardson",
  "Teresa Cox",
  "Bryan Howard",
  "Sara Ward",
  "Joe Torres",
  "Janice Peterson",
  "Jordan Gray",
  "Doris Ramirez",
  "Billy James",
  "Monica Watson",
  "Bruce Brooks",
  "Debra Kelly",
  "Albert Sanders",
  "Rachel Price",
  "Willie Bennett",
  "Catherine Wood",
  "Gabriel Barnes",
  "Carolyn Ross",
  "Logan Henderson",
  "Janet Coleman",
  "Alan Jenkins",
  "Ruth Perry",
  "Juan Powell",
  "Maria Long"
]

export const last_names = [
  "Smith",
  "Graham",
  "Kim",
  "Burke",
  "Patel",
  "Kennedy",
  "Owen",
  "Schmidt",
  "Castillo",
  "Curtis",
  "Christensen",
  "Arnold",
  "Douglas",
  "Willis",
  "Ray",
  "Sutton",
  "Ortega",
  "Jensen",
  "Carlson",
  "connor",
  "Marshall",
  "Mcdaniel",
  "Alvarez",
  "Avery",
  "Moreno",
  "Bowman",
  "Medina",
  "Fowler",
  "Brewer",
  "Hoffman",
  "Carlton",
  "Silva",
  "Pearson",
  "Holland",
  "Douglas",
  "Fleming",
  "Jensen",
  "Vargas",
  "Byrd",
  "Davidson",
  "Hopkins",
  "May",
  "Terry",
  "Herrera",
  "Wade",
  "Soto",
  "Walters",
  "Curtis",
  "Neal",
  "Caldwell",
  "Lowe",
  "Jennings",
  "Barnett",
  "Graves",
  "Jimenez",
  "Horton",
  "Shelton",
  "Barrett",
  "Obrien",
  "Castro",
  "Sutton",
  "Gregory",
  "McKinney",
  "Lucas",
  "Miles",
  "Craig",
  "Rodriquez",
  "Chambers",
  "Holt",
  "Lambert",
  "Fletcher",
  "Watts",
  "Bates",
  "Hale",
  "Rhodes",
  "Pena",
  "Beck",
  "Newman",
  "Haynes",
  "Mcfarland",
  "Sparks",
  "Wiley",
  "Davidson",
  "Huang",
  "Kemp",
  "Rivers",
  "Ochoa",
  "Bradshaw",
  "Foreman",
  "Johnson",
  "Williams",
  "Jones",
  "Brown",
  "Davis",
  "Miller",
  "Wilson",
  "Moore",
  "Taylor",
  "Anderson",
  "Thomas",
  "Jackson",
  "White",
  "Harris",
  "Martin",
  "Thompson",
  "Garcia",
  "Martinez",
  "Robinson",
  "Clark",
  "Rodriguez",
  "Lewis",
  "Lee",
  "Walker",
  "Hall",
  "Allen",
  "Young",
  "Hernandez",
  "King",
  "Wright",
  "Lopez",
  "Hill",
  "Scott",
  "Green",
  "Adams",
  "Baker",
  "Gonzalez",
  "Nelson",
  "Carter",
  "Mitchell",
  "Perez",
  "Roberts",
  "Turner",
  "Phillips",
  "Campbell",
  "Parker",
  "Evans",
  "Edwards",
  "Collins",
  "Stewart",
  "Sanchez",
  "Morris",
  "Rogers",
  "Reed",
  "Cook",
  "Morgan",
  "Bell",
  "Murphy",
  "Bailey",
  "Rivera",
  "Cooper",
  "Richardson",
  "Cox",
  "Howard",
  "Ward",
  "Torres",
  "Peterson",
  "Gray",
  "Ramirez",
  "James",
  "Watson",
  "Brooks",
  "Kelly",
  "Sanders",
  "Price",
  "Bennett",
  "Wood",
  "Barnes",
  "Ross",
  "Henderson",
  "Coleman",
  "Jenkins",
  "Perry",
  "Powell",
  "Long",
  "Patterson",
  "Hughes",
  "Flores",
  "Washington",
  "Butler",
  "Simmons",
  "Foster",
  "Gonzales",
  "Bryant",
  "Alexander",
  "Russell",
  "Griffin",
  "Diaz",
  "Hayes",
];
export const first_names = [
  "John",
  "Mary",
  "James",
  "Patricia",
  "Robert",
  "Jennifer",
  "Michael",
  "Linda",
  "William",
  "Elizabeth",
  "David",
  "Barbara",
  "Richard",
  "Susan",
  "Joseph",
  "Jessica",
  "Thomas",
  "Sarah",
  "Charles",
  "Karen",
  "Christopher",
  "Nancy",
  "Daniel",
  "Lisa",
  "Matthew",
  "Betty",
  "Anthony",
  "Margaret",
  "Mark",
  "Sandra",
  "Donald",
  "Ashley",
  "Steven",
  "Kimberly",
  "Paul",
  "Emily",
  "Andrew",
  "Donna",
  "Joshua",
  "Michelle",
  "Kenneth",
  "Dorothy",
  "Kevin",
  "Carol",
  "Brian",
  "Amanda",
  "George",
  "Melissa",
  "Edward",
  "Deborah",
  "Ronald",
  "Stephanie",
  "Timothy",
  "Rebecca",
  "Jason",
  "Sharon",
  "Jeffrey",
  "Laura",
  "Ryan",
  "Cynthia",
  "Jacob",
  "Kathleen",
  "Gary",
  "Amy",
  "Nicholas",
  "Shirley",
  "Eric",
  "Angela",
  "Jonathan",
  "Helen",
  "Stephen",
  "Anna",
  "Larry",
  "Brenda",
  "Justin",
  "Pamela",
  "Scott",
  "Nicole",
  "Brandon",
  "Emma",
  "Benjamin",
  "Samantha",
  "Samuel",
  "Katherine",
  "Gregory",
  "Christine",
  "Frank",
  "Debra",
  "Alexander",
  "Rachel",
  "Raymond",
  "Catherine",
  "Patrick",
  "Carolyn",
  "Jack",
  "Janet",
  "Dennis",
  "Ruth",
  "Jerry",
  "Maria",
  "Tyler",
  "Heather",
  "Aaron",
  "Diane",
  "Jose",
  "Virginia",
  "Adam",
  "Julie",
  "Henry",
  "Joyce",
  "Nathan",
  "Victoria",
  "Douglas",
  "Olivia",
  "Zachary",
  "Kelly",
  "Peter",
  "Christina",
  "Kyle",
  "Lauren",
  "Walter",
  "Joan",
  "Ethan",
  "Evelyn",
  "Jeremy",
  "Judith",
  "Harold",
  "Megan",
  "Keith",
  "Cheryl",
  "Christian",
  "Andrea",
  "Roger",
  "Hannah",
  "Gerald",
  "Martha",
  "Carl",
  "Jacqueline",
  "Terry",
  "Frances",
  "Sean",
  "Ann",
  "Austin",
  "Gloria",
  "Arthur",
  "Jean",
  "Lawrence",
  "Kathryn",
  "Jesse",
  "Alice",
  "Dylan",
  "Teresa",
  "Bryan",
  "Sara",
  "Joe",
  "Janice",
  "Jordan",
  "Doris",
  "Billy",
  "Monica",
  "Bruce",
  "Debra",
  "Albert",
  "Rachel",
  "Willie",
  "Catherine",
  "Gabriel",
  "Carolyn",
  "Logan",
  "Janet",
  "Alan",
  "Ruth",
  "Juan",
  "Maria",
  "Wayne",
  "Heather",
  "Roy",
  "Diane",
  "Ralph",
  "Virginia",
  "Randy",
  "Julie",
  "Eugene",
  "Joyce",
  "Vincent",
  "Victoria",
  "Russell",
  "Kelly",
  "Elijah",
  "Christina",
  "Louis",
  "Lauren",
  "Bobby",
  "Joan",
  "Philip",
  "Evelyn",
  "Johnny",
  "Judith",
  "Bradley",
  "Megan",
  "Jesus",
  "Cheryl",
  "Frederick",
  "Andrea",
  "Ray",
  "Hannah",
  "Joel",
  "Martha",
  "Eduardo",
  "Jacqueline",
  "Max",
  "Frances",
  "Noah",
  "Ann",
  "Oscar",
  "Gloria",
  "Terrance",
  "Jean",
  "Wesley",
  "Kathryn",
  "Stanley",
  "Alice",
  "Ernest",
  "Teresa",
  "Nathaniel",
  "Sara",
  "Miguel",
  "Janice",
  "Francis",
  "Doris",
  "Leonard",
  "Monica",
  "Chester",
  "Patricia",
];

export const parent_names = [
  "Kayla Smith",
  "Tiffany Graham",
  "Lori Kim",
  "Jane Burke",
  "Diana Patel",
  "Brittany Kennedy",
  "Rose Owen",
  "Danielle Schmidt",
  "Amber Castillo",
  "Marilyn Curtis",
  "Denise Christensen",
  "Beverly Arnold",
  "Theresa Douglas",
  "Marie Willis",
  "Eileen Ray",
  "Jacqueline Sutton",
  "Hannah Ortega",
  "Kathryn Jensen",
  "Gloria Carlson",
  "Doris connor",
  "Ann Marshall",
  "Alice Mcdaniel",
  "Jean Alvarez",
  "Olivia Avery",
  "Andrea Moreno",
  "Megan Bowman",
  "Cheryl Medina",
  "Judith Fowler",
  "Martha Brewer",
  "Frances Hoffman",
  "Lauren Carlton",
  "Christina Silva",
  "Kelly Pearson",
  "Victoria Holland",
  "Joan Douglas",
  "Evelyn Fleming",
  "Joyce Jensen",
  "Julie Vargas",
  "Diane Byrd",
  "Heather Davidson",
  "Maria Hopkins",
  "Virginia May",
  "Catherine Terry",
  "Janet Herrera",
  "Carolyn Wade",
  "Rachel Soto",
  "Debra Walters",
  "Christine Curtis",
  "Katherine Neal",
  "Samantha Caldwell",
  "Emma Lowe",
  "Nicole Jennings",
  "Pamela Barnett",
  "Brenda Graves",
  "Anna Jimenez",
  "Helen Horton",
  "Angela Shelton",
  "Shirley Barrett",
  "Amy Obrien",
  "Kathleen Castro",
  "Cynthia Sutton",
  "Laura Gregory",
  "Sharon McKinney",
  "Rebecca Lucas",
  "Stephanie Miles",
  "Deborah Craig",
  "Michelle Rodriquez",
  "Donna Chambers",
  "Melissa Holt",
  "Amanda Lambert",
  "Carol Fletcher",
  "Dorothy Watts",
  "Michelle Bates",
  "Lisa Hale",
  "Nancy Rhodes",
  "Karen Pena",
  "Sarah Beck",
  "Jessica Newman",
  "Susan Haynes",
  "Barbara Mcfarland",
  "Elizabeth Sparks",
  "Linda Wiley",
  "Jennifer Davidson",
  "Patricia Huang",
  "Mary Kemp",
  "Johnny Rivers",
  "Philip Ochoa",
  "Bobby Bradshaw",
  "Louis Foreman",
  "Elijah Johnson",
  "Russell Williams",
  "Vincent Jones",
  "Eugene Brown",
  "Randy Davis",
  "Ralph Miller",
  "Roy Wilson",
  "Wayne Moore",
  "Alan Taylor",
  "Logan Anderson",
  "Gabriel Thomas",
  "Willie Jackson",
  "Bruce White",
  "Bryan Harris",
  "Billy Martin",
  "Jordan Thompson",
  "Joe Garcia",
  "Ethan Martinez",
  "Jeremy Robinson",
  "Carl Clark",
  "Jack Rodriguez",
  "Dale Lewis",
  "Jesse Lee",
  "Harold Walker",
  "Arthur Hall",
  "Austin Allen",
  "Sean Young",
  "Lawrence Hernandez",
  "Terry King",
  "Keith Wright",
  "Gerald Lopez",
  "Noah Hill",
  "Roger Scott",
  "Christian Green",
  "Brandon Adams",
  "Samuel Baker",
  "Albert Gonzalez",
  "Dylan Nelson",
  "Jose Carter",
  "Zachary Mitchell",
  "Nathan Perez",
  "Henry Roberts",
  "Aaron Turner",
  "Tyler Phillips",
  "Dennis Campbell",
  "Jerry Parker",
  "Adam Evans",
  "Peter Edwards",
  "Jonathan Collins",
  "Benjamin Stewart",
  "Nicholas Sanchez",
  "Walter Morris",
  "Ryan Rogers",
  "Douglas Reed",
  "Alexander Cook",
  "Raymond Morgan",
  "Gregory Bell",
  "Patrick Murphy",
  "Frank Bailey",
  "Scott Rivera",
  "Stephen Cooper",
  "Eric Richardson",
  "Joshua Cox",
  "Paul Howard",
  "Daniel Ward",
  "Christopher Torres",
  "Gary Peterson",
  "Matthew Gray",
  "Jason Ramirez",
  "Joseph James",
  "Charles Watson",
  "Ronald Brooks",
  "Edward Kelly",
  "George Sanders",
  "Brian Price",
  "Kevin Bennett",
  "Kenneth Wood",
  "Andrew Barnes",
  "Timothy Ross",
  "Steven Henderson",
  "Thomas Coleman",
  "Richard Jenkins",
  "William Perry",
  "Mark Powell",
  "Robert Long"
]

export const parent_first_names = ['Kayla', 'Tiffany', 'Lori', 'Jane', 'Diana', 'Brittany', 'Rose', 'Danielle', 'Amber', 'Marilyn', 'Denise', 'Beverly', 'Theresa', 'Marie', 'Eileen', 'Jacqueline', 'Hannah', 'Kathryn', 'Gloria', 'Doris', 'Ann', 'Alice', 'Jean', 'Olivia', 'Andrea', 'Megan', 'Cheryl', 'Judith', 'Martha', 'Frances', 'Lauren', 'Christina', 'Kelly', 'Victoria', 'Joan', 'Evelyn', 'Joyce', 'Julie', 'Diane', 'Heather', 'Maria', 'Virginia', 'Catherine', 'Janet', 'Carolyn', 'Rachel', 'Debra', 'Christine', 'Katherine', 'Samantha', 'Emma', 'Nicole', 'Pamela', 'Brenda', 'Anna', 'Helen', 'Angela', 'Shirley', 'Amy', 'Kathleen', 'Cynthia', 'Laura', 'Sharon', 'Rebecca', 'Stephanie', 'Deborah', 'Michelle', 'Donna', 'Melissa', 'Amanda', 'Carol', 'Dorothy', 'Michelle', 'Lisa', 'Nancy', 'Karen', 'Sarah', 'Jessica', 'Susan', 'Barbara', 'Elizabeth', 'Linda', 'Jennifer', 'Patricia', 'Mary', 'Johnny', 'Philip', 'Bobby', 'Louis', 'Elijah', 'Russell', 'Vincent', 'Eugene', 'Randy', 'Ralph', 'Roy', 'Wayne', 'Alan', 'Logan', 'Gabriel', 'Willie', 'Bruce', 'Bryan', 'Billy', 'Jordan', 'Joe', 'Ethan', 'Jeremy', 'Carl', 'Jack', 'Dale', 'Jesse', 'Harold', 'Arthur', 'Austin', 'Sean', 'Lawrence', 'Terry', 'Keith', 'Gerald', 'Noah', 'Roger', 'Christian', 'Brandon', 'Samuel', 'Albert', 'Dylan', 'Jose', 'Zachary', 'Nathan', 'Henry', 'Aaron', 'Tyler', 'Dennis', 'Jerry', 'Adam', 'Peter', 'Jonathan', 'Benjamin', 'Nicholas', 'Walter', 'Ryan', 'Douglas', 'Alexander', 'Raymond', 'Gregory', 'Patrick', 'Frank', 'Scott', 'Stephen', 'Eric', 'Joshua', 'Paul', 'Daniel', 'Christopher', 'Gary', 'Matthew', 'Jason', 'Joseph', 'Charles', 'Ronald', 'Edward', 'George', 'Brian', 'Kevin', 'Kenneth', 'Andrew', 'Timothy', 'Steven', 'Thomas', 'Richard', 'William', 'Mark', 'Robert', 'James', 'David', 'Michael', 'John']

export const streams = [
  { "id": "641ca7dbbe8caf6d48376e4d", "name": "1 North", "slug": "1n", "deleted": false },
  { "id": "641ca7debe8caf6d48376e4f", "name": "1 West", "slug": "1w", "deleted": false },
  { "id": "641ca7dfbe8caf6d48376e50", "name": "2 North", "slug": "2n", "deleted": false },
  { "id": "641ca7e0be8caf6d48376e51", "name": "1 South", "slug": "1s", "deleted": false },
  { "id": "641ca7e1be8caf6d48376e52", "name": "2 West", "slug": "2w", "deleted": false },
  { "id": "641ca7e3be8caf6d48376e53", "name": "2 South", "slug": "2s", "deleted": false },
  { "id": "641ca7e7be8caf6d48376e56", "name": "3 North", "slug": "3n", "deleted": false },
  { "id": "64b5ad3c7aa95312a4655b30", "name": "3 West", "slug": "3w", "deleted": false },
  { "id": "64b5ad637aa95312a4655b31", "name": "3 South", "slug": "3s", "deleted": false },
  { "id": "64b5ad817aa95312a4655b32", "name": "4 South", "slug": "4s", "deleted": false },
  { "id": "64b5ad9a7aa95312a4655b33", "name": "4 West", "slug": "4w", "deleted": false },
  { "id": "64b5adb27aa95312a4655b34", "name": "4 North", "slug": "4n", "deleted": false },
]

export const allStudents = []

export const male_names = [
  'John', 'James', 'Robert', 'Michael', 'William', 'David', 'Richard', 'Joseph', 'Thomas', 'Charles', 'Daniel', 'Matthew',
  'Anthony', 'Mark', 'Donald', 'Steven', 'Paul', 'Andrew', 'Joshua', 'Kenneth', 'Kevin', 'Brian', 'George', 'Edward',
  'Ronald', 'Timothy', 'Jason', 'Jeffrey', 'Ryan', 'Jacob', 'Gary', 'Nicholas', 'Eric', 'Jonathan', 'Stephen', 'Larry',
  'Justin', 'Scott', 'Brandon', 'Benjamin', 'Samuel', 'Gregory', 'Frank', 'Alexander', 'Patrick', 'Jack', 'Dennis', 'Jerry',
  'Tyler', 'Aaron', 'Jose', 'Adam', 'Henry', 'Nathan', 'Douglas', 'Zachary', 'Peter', 'Kyle', 'Walter', 'Ethan', 'Jeremy',
  'Harold', 'Keith', 'Christian', 'Roger', 'Gerald', 'Carl', 'Sean', 'Austin', 'Arthur', 'Lawrence', 'Jesse', 'Dylan', 'Bryan',
  'Joe', 'Jordan', 'Billy', 'Albert', 'Willie', 'Gabriel', 'Alan', 'Juan', 'Wayne', 'Roy', 'Ralph', 'Russell', 'Elijah', 'Louis',
  'Bobby', 'Johnny', 'Bradley', 'Jesus', 'Frederick', 'Ray', 'Joel', 'Eduardo', 'Max', 'Noah', 'Oscar', 'Terrance', 'Wesley', 'Christopher',
  'Stanley', 'Ernest', 'Nathaniel', 'Miguel', 'Francis', 'Leonard', 'Chester']

export const female_names = [
  'Mary', 'Patricia', 'Jennifer', 'Linda', 'Elizabeth', 'Barbara', 'Susan', 'Jessica', 'Sarah', 'Karen', 'Nancy', 'Lisa',
  'Betty', 'Margaret', 'Sandra', 'Ashley', 'Kimberly', 'Dorothy', 'Carol', 'Amanda', 'Melissa', 'Deborah', 'Stephanie',
  'Rebecca', 'Sharon', 'Laura', 'Cynthia', 'Kathleen', 'Amy', 'Shirley', 'Angela',
  'Helen', 'Anna', 'Brenda', 'Pamela', 'Nicole', 'Emma', 'Samantha', 'Katherine',
  'Christine', 'Debra', 'Rachel', 'Catherine', 'Diane', 'Jessica', 'Heather',
  'Donna', 'Michelle', 'Julia', 'Virginia', 'Kelly', 'Christina', 'Evelyn',
  'Judith', 'Megan', 'Cheryl', 'Amber', 'Joan', 'Emily', 'Olivia', 'Victoria',
  'Gloria', 'Jean', 'Kathryn', 'Janet', 'Alice', 'Teresa', 'Sara', 'Janice',
  'Ruth', 'Maria', 'Hannah', 'Frances', 'Ann', 'Doris', 'Monica', 'Janet', 'Carolyn']